opt_in_rules:
  - empty_count
  - contains_over_first_not_nil
  - fatal_error_message
  - first_where
  - number_separator
  - operator_usage_whitespace
  - trailing_closure

function_parameter_count:
  warning: 3
  error: 4

line_length:
  ignores_function_declarations: true
  ignores_comments: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 600

large_tuple:
  warning: 3
  error: 4

identifier_name:
  excluded:
    - to
    - id
    - x
    - y
    - i
    - j

reporter: "xcode"

