name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        run-config:
          - { scheme: 'DEViOSTests', destination: 'platform=iOS Simulator,OS=14.4,name=iPhone 12' }
          #- { scheme: 'DEV (macOS)', destination: 'platform=macOS' }

    steps:
    - name: Checkout Project
      uses: actions/checkout@v1

    - name: Show the currently detailed version of Xcode for CLI
      run: xcode-select -p

    - name: build and test
      run: xcodebuild clean test -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -showBuildTimingSummary
