name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        run-config:
          - { scheme: 'DEViOSTests', destination: 'platform=iOS Simulator,OS=14.4,name=iPhone 12' }

    steps:
    - name: Checkout Project
      uses: actions/checkout@v1

    - name: Show the currently detailed version of Xcode for CLI
      run: xcode-select -p

    - name: build API package
      run: swift build --package-path ./DEVAPI -v

    - name: test API package
      run: swift test --package-path ./DEVAPI -v

    - name: build and test
      run: xcodebuild clean test -workspace "DEV.xcworkspace" -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -showBuildTimingSummary
